ROB: Handle missing destinations in reader (#840)
If a destination is missing, getDestinationPageNumber now returns -1
If `strict=False`, the first page is used as a fallback.

The code triggering the exception was

```python
from PyPDF2 import PdfFileReader

# https://github.com/mstamy2/PyPDF2/files/6045010/thyroid.pdf
with open("thyroid.pdf", "rb") as f:
   reader = PdfFileReader(f)
   bookmarks = pdf.getOutlines()
   for b in bookmarks:
       print(reader.getDestinationPageNumber(b) + 1)  # page count starts from 0
```

The error message was:
    PyPDF2.utils.PdfReadError: Unknown Destination Type: 0

Closes #604 
Closes #821