BUG: _rebuild_xref_table expects trailer to be a dict (#857)
This caused:
    AttributeError: 'FloatObject' object has no attribute 'items'

Closes #856

Co-authored-by: pubpub-zz <4083478+pubpub-zz@users.noreply.github.com>