Fix getObject on missing '/Annots'
Traceback (most recent call last):
  File "/home/edegoute/Repositories/proxy.pdf/proxy/pdf/views.py", line 224, in generatePdf
    watermark(tmp_prince_output.name, tmp_specimen_output.name)
  File "/home/edegoute/Repositories/proxy.pdf/proxy/pdf/watermark.py", line 15, in watermark
    page.mergePage(watermark.getPage(0))
  File "/home/edegoute/Repositories/proxy.pdf/eggs/PyPDF3-1.0.1-py2.7.egg/PyPDF3/pdf.py", line 2380, in mergePage
    self._mergePage(page2)
  File "/home/edegoute/Repositories/proxy.pdf/eggs/PyPDF3-1.0.1-py2.7.egg/PyPDF3/pdf.py", line 2395, in _mergePage
    annots = page["/Annots"]
  File "/home/edegoute/Repositories/proxy.pdf/eggs/PyPDF3-1.0.1-py2.7.egg/PyPDF3/generic.py", line 518, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "/home/edegoute/Repositories/proxy.pdf/eggs/PyPDF3-1.0.1-py2.7.egg/PyPDF3/generic.py", line 179, in getObject
    return self.pdf.getObject(self).getObject()
AttributeError: 'NoneType' object has no attribute 'getObject'