Handle cases where /DecodeParms is an ArrayObject
Fixes bug where decodeParms.get(...) causes
AttributeError: 'ArrayObject' object has no attribute 'get'