pdf sample which breaks merger
/Users/eric/.virtualenvs/regluit/lib/python2.7/site-packages/PyPDF2/merg
er.pyc in append(self, fileobj, bookmark, pages, import_bookmarks)
    196         """
    197
--> 198         self.merge(len(self.pages), fileobj, bookmark, pages,
import_bookmarks)
    199
    200

/Users/eric/.virtualenvs/regluit/lib/python2.7/site-packages/PyPDF2/merg
er.pyc in merge(self, position, fileobj, bookmark, pages,
import_bookmarks)
    151
    152         dests = pdfr.namedDestinations
--> 153         dests = self._trim_dests(pdfr, dests, pages)
    154         self.named_dests += dests
    155

/Users/eric/.virtualenvs/regluit/lib/python2.7/site-packages/PyPDF2/merg
er.pyc in _trim_dests(self, pdf, dests, pages)
    299                 if pdf.getPage(j).getObject() ==
o['/Page'].getObject():
    300                     o[NameObject('/Page')] =
o['/Page'].getObject()
--> 301                     assert str(k) == str(o['/Title'])
    302                     new_dests.append(o)
    303                     break

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in
position 28: ordinal not in range(128)